source/objects/Bluescape_Demo__c/Bluescape_Demo__c.object-meta.xml
<CustomObject>
    <description>External Bluescape Events, including Demo Installation requests</description>
    <label>Bluescape Demo</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bluescape Demos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Demo__c/fields/Created_Admin_User_For_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Created_Admin_User_For_Primary_Contact__c</fullName>
    <label>Admin User For Primary Contact Created</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <label>Org ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who to contact for scheduling shipping, installation and removal of the demo unit</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

source/classes/BluescapeDemoPrimaryContactAdminUser.cls
public class BluescapeDemoPrimaryContactAdminUser {

	@InvocableMethod (label = 'Bluescape Demo Create Primary Contact Admin User')
	public static void createAdminUser(List<Id> bluescapeDemoIds) {
		createUser(bluescapeDemoIds[0]);
	}

	@future (callout = true)
	public static void createUser(Id bluescapeDemoId) {
		Bluescape_Demo__c bluescapeDemo = [
				SELECT
					Org_Id__c, Owner.Email, Primary_Contact__r.Email, Created_Admin_User_For_Primary_Contact__c
				FROM
					Bluescape_Demo__c
				WHERE
					Id = :bluescapeDemoId
		];

		if (bluescapeDemo.Org_Id__c == null || bluescapeDemo.Primary_Contact__r.Email == null) return;

		Integer orgId = Integer.valueOf(bluescapeDemo.Org_Id__c);
		String email = bluescapeDemo.Primary_Contact__r.Email;

		Boolean createAdminUserSuccess = UtilIntegration.createAdminUser(orgId, email, false);

		if (createAdminUserSuccess) {
			bluescapeDemo.Created_Admin_User_For_Primary_Contact__c = 'Success';
		} else {
			bluescapeDemo.Created_Admin_User_For_Primary_Contact__c = 'Fail';
		}

		if (createAdminUserSuccess) {
			Contact primaryContact = [
					SELECT
						Org_Id__c
					FROM
						Contact
					WHERE
						Id = :bluescapeDemo.Primary_Contact__c
			];

			if (primaryContact.Org_Id__c == null) {
				primaryContact.Org_Id__c = bluescapeDemo.Org_Id__c;
			} else {
				primaryContact.Org_Id__c += ', ' + bluescapeDemo.Org_Id__c;
			}

			update primaryContact;
		}

		UtilIntegration.updateBluescapeAPIInfo();

		update bluescapeDemo;
	}
}