source/objects/BluescapeSupport_Site_Category__c/BluescapeSupport_Site_Category__c.object-meta.xml
<CustomObject>
    <label>Support Site Category</label>
    <nameField>
        <label>Site Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Site Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/BluescapeSupport_Site_Category__c/fields/IconName__c.field-meta.xml
<CustomField>
    <fullName>IconName__c</fullName>
    <label>IconName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/classes/BluescapeSupport_NavController.cls
global class BluescapeSupport_NavController
{
    public List<SiteCategory> siteCategories { get; set; }

    public BluescapeSupport_NavController()
    {
        loadSiteCategories();
    }

    private void loadSiteCategories()
    {
        siteCategories = new List<SiteCategory>();

        List<BluescapeSupport_Site_Category__c> cats = [SELECT Name, IconName__c, Active__c FROM BluescapeSupport_Site_Category__c WHERE Active__c = true ORDER BY Display_Sequence__c ASC];

        for (BluescapeSupport_Site_Category__c cat : cats)
        {
            SiteCategory siteCategory = new SiteCategory(cat.Name);
            siteCategories.add(siteCategory);
        }
    }

    global class SiteCategory
    {
        public String name { get; set; }

        public SiteCategory(String name)
        {
            this.name = name;
        }
    }
}