source/objects/Bluescape_Org__c/Bluescape_Org__c.object-meta.xml
<CustomObject>
    <description>Bluescape Portal Organization</description>
    <label>Bluescape Org</label>
    <nameField>
        <label>Bluescape Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Org__c/fields/Bluescape_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org_ID__c</fullName>
    <externalId>true</externalId>
    <label>Bluescape Org ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

source/objects/ContactBluescapeOrg__c/ContactBluescapeOrg__c.object-meta.xml
<CustomObject>
    <description>The many to many association between Portal Users (Contacts flaged as Portal Users) and Bluescape Org&#39;s</description>
    <label>ContactBluescapeOrg</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ContactBluescapeOrg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ContactBluescapeOrgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/objects/ContactBluescapeOrg__c/fields/Bluescape_Org__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org__c</fullName>
    <label>Bluescape Org</label>
    <referenceTo>Bluescape_Org__c</referenceTo>
    <relationshipLabel>Portal Users</relationshipLabel>
    <relationshipName>ContactBluescapeOrgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/objects/ContactBluescapeOrg__c/fields/Extension_Duration__c.field-meta.xml
<CustomField>
    <fullName>Extension_Duration__c</fullName>
    <label>Extension Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Extension_Duration</valueSetName>
    </valueSet>
</CustomField>

source/objects/ContactBluescapeOrg__c/fields/Trial_Extended__c.field-meta.xml
<CustomField>
    <fullName>Trial_Extended__c</fullName>
    <label>Trial Extended</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trial_Extended</valueSetName>
    </valueSet>
</CustomField>

source/classes/BluescapeExtendingOrgExpiration.cls
public class BluescapeExtendingOrgExpiration {
    @InvocableMethod (label = 'Extending Org Expiration')
    public static void extendingOrgExpiration(List<Id> recordIds) {
        extendingOrgExpirationFuture(recordIds[0]);
    }
    
    @future (callout = true)
    public static void extendingOrgExpirationFuture(Id recordId) {
        String sObjectName = String.valueOf(recordId.getSObjectType());
        String queryStr;
        String orgRootUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/';
        String htmlRecordUrl = '<a href="' + orgRootUrl + recordId + '" target="_blank">' + orgRootUrl + recordId + '</a>';

        if (sObjectName == 'ContactBluescapeOrg__c') {
           queryStr  = 'SELECT Bluescape_Org__r.Bluescape_Org_Id__c, Extension_Duration__c FROM ' + sObjectName + ' WHERE Id = :recordId';
        } else {
            queryStr = 'SELECT Org_Id__c, Extension_Duration__c FROM ' + sObjectName + ' WHERE Id = :recordId';
        }
        
        sObject sobj = Database.query(queryStr);

        Integer orgId = sObjectName == 'ContactBluescapeOrg__c' ? 
                                        Integer.valueOf(sobj.getSObject('Bluescape_Org__r').get('Bluescape_Org_Id__c')) : 
                                        Integer.valueOf(sobj.get('Org_Id__c'));
        Integer extensionDuration = Integer.valueOf(sobj.get('Extension_Duration__c'));
        
        try {
            BluescapeIntegration.extendingOrgExpiration(orgId, extensionDuration);
            saveExtendingResult(sObjectName, recordId, 'Success');
            
        } catch (BluescapeIntegration.ResponseException e) {
            saveExtendingResult(sObjectName, recordId, 'Fail');

            if (!Test.isRunningTest()){
                String msgHtmlBody = '<p>Org Duration Extension process failed, retry please.</p>';
                msgHtmlBody += '<p>' + e.getMessage() + '</p>' + '<p>' + htmlRecordUrl + '</p>';
                EmailManager.sendEmail(new List<String> {UtilIntegration.getErrorEmailAddress()}, 'Bluescape Demo Org Duration Extension Failed', msgHtmlBody);
            }
        }     
    }
    
    private static void saveExtendingResult(String sObjectName, Id recordId, String status) {
        String queryStr = 'SELECT Trial_Extended__c FROM ' + sObjectName + ' WHERE Id = :recordId';
        sObject sObj = Database.query(queryStr);
        sObj.put('Trial_Extended__c', status);
        
        update sObj;
    }
}