source/objects/RS_Sales_Order_Extension__c/RS_Sales_Order_Extension__c.object-meta.xml
<CustomObject>
    <label>RS Sales Order Extension</label>
    <nameField>
        <displayFormat>SOE-{000000}</displayFormat>
        <label>RS Sales Order Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RS Sales Order Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/objects/RS_Sales_Order_Extension__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account associated to the Sales Order Header.  This field is set via trigger &#39;SetLookupFields&#39;</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RS Sales Order Extensions</relationshipLabel>
    <relationshipName>RS_Sales_Order_Extensions</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/RS_Sales_Order_Extension__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity on the Sales Order.  This field is set via the trigger &#39;SetLookupFields&#39;</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RS Sales Order Extensions</relationshipLabel>
    <relationshipName>RS_Sales_Order_Extensions</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/RS_Sales_Order_Extension__c/fields/Sales_Order_Header__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Header__c</fullName>
    <description>Rootstock Sales Order</description>
    <inlineHelpText>Rootstock Sales Order</inlineHelpText>
    <label>Rootstock Sales Order</label>
    <referenceTo>rstk__sohdr__c</referenceTo>
    <relationshipLabel>RS Sales Order Extensions1x</relationshipLabel>
    <relationshipName>RS_Sales_Order_Extensions1x</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/classes/TestSetLookupFields.cls
@isTest(SeeAllData=true)
public class TestSetLookupFields {
    static testMethod void myUnitTest() {
        rstk__sohdr__c soh = [select Id, rstk__sohdr_opportunity__c, rstk__sohdr_account__c from rstk__sohdr__c where Id = : 'a5NE0000000fxo2'];
        RS_Sales_Order_Extension__c  soe = new RS_Sales_Order_Extension__c();
        soe.Sales_Order_Header__c = soh.Id;
        insert soe;
        
        RS_Sales_Order_Extension__c soe2 = [select Id, Opportunity__c, Account__c from RS_Sales_Order_Extension__c where Id = : soe.Id];
        System.assert(soh.rstk__sohdr_opportunity__c == soe2.Opportunity__c);
        System.assert(soh.rstk__sohdr_account__c == soe2.Account__c);
    }
}