source/objects/Entitlement_Template__c/Entitlement_Template__c.object-meta.xml
<CustomObject>
    <label>Entitlement Template</label>
    <nameField>
        <label>Entitlement Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Entitlement_Template__c/fields/Entitlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Type__c</fullName>
    <label>Entitlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>User Licenses</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Entitlement_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entitlement Templates</relationshipLabel>
    <relationshipName>Entitlement_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Entitlement_Template__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>If Use Template Quantity is checked value from this field will be used as Entitlement Quantity.</description>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

source/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Sales_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N40000001jWqAEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Sales_Order__c/fields/Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Install_Date__c</fullName>
    <description>Date of Installation needed by account for rev rec</description>
    <inlineHelpText>Date of Installaion and accounting revenue recognition</inlineHelpText>
    <label>Install Date</label>
    <type>Date</type>
</CustomField>

source/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This is to track fulfillment of the order</description>
    <inlineHelpText>This field tracks fulfillment of the order</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Sales_Order_Item__c/Sales_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Line items for Sales Order document.</description>
    <label>Sales Order Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/objects/Sales_Order_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

source/objects/Sales_Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

source/objects/Sales_Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>R00N40000001jWpEEAU</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/classes/TestServiceContract.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class TestServiceContract {

    static testMethod void myUnitTest() {
        Account account = createAccount();
        System.assert(account != null);
        Contact contact = createContact(account);
        System.assert(contact != null);
        Product2 product = createProduct();
        System.assert(product != null);
        Entitlement_Template__c entitlementTemplate = createEntitlementTemplate(product);
        System.assert(entitlementTemplate != null);
        PricebookEntry priceBookEntry = createPricebookEntry(product);
        System.assert(priceBookEntry != null);
        Sales_Order__c salesOrder = createSalesOrder(account);
        System.assert(salesOrder != null);
        Sales_Order_Item__c salesOrderLine = createSalesOrderLine(salesOrder, product.ProductCode, 5, priceBookEntry.UnitPrice);
        System.assert(salesOrderLine != null);

        String scNumber = SalesOrderUtils.createServiceContract(salesOrder.Id);
        System.debug(' >>>>>>> SC Number : ' + scNumber);
        System.assert(scNumber != null);
        
        ServiceContract serviceContract = [select Id from ServiceContract where Sales_Order__c = :salesOrder.Id];
        System.assert(serviceContract != null);
        
        salesOrder.Install_Date__c = Date.today();
        salesOrder.Status__c = 'Installed';
        update salesOrder;
    }
    
    public static Account createAccount() {
        Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        return account;
    }

    public static Contact createContact(Account account) {
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'Contact';
        contact.AccountId = account.Id;
        insert contact;
        return contact;
    }

    public static Product2 createProduct() {
        Product2 product = new Product2();
        product.Name = 'Test Product';
        product.ProductCode = 'SR_TEST_PRODUCT';
        product.Family = 'IsActive';
        product.IsActive = true;
        insert product;
        return product;
    }

    public static PricebookEntry createPricebookEntry(Product2 product2) {
        PricebookEntry priceBookEntry = new PricebookEntry();
        priceBookEntry.Pricebook2Id = Test.getStandardPricebookId();
        priceBookEntry.Product2Id = product2.Id;
        priceBookEntry.UnitPrice = 5000;
        priceBookEntry.IsActive = true;
        insert priceBookEntry;
        return priceBookEntry;
    }

    public static Entitlement_Template__c createEntitlementTemplate(Product2 product2) {
        Entitlement_Template__c entitlementTemplate = new Entitlement_Template__c();
        entitlementTemplate.Name = 'Warranty';
        entitlementTemplate.Entitlement_Type__c = 'Warranty';
        entitlementTemplate.Product__c = product2.Id;
        insert entitlementTemplate;
        return entitlementTemplate;
    }

    public static Sales_Order__c createSalesOrder(Account account) {
        Sales_Order__c salesOrder = new Sales_Order__c();
        salesOrder.Name = 'Test Sales Order';
        salesOrder.Account__c = account.Id;
        salesOrder.Status__c = 'Open';
        insert salesOrder;
        return salesOrder;
    }

    public static Sales_Order_Item__c createSalesOrderLine(Sales_Order__c salesOrder, String itemCode, Integer quantity, Decimal price) {
        Sales_Order_Item__c salesOrderLine = new Sales_Order_Item__c();
        salesOrderLine.Name = 'Test Sales Order Line';
        salesOrderLine.Sales_Order__c = salesOrder.Id;
        salesOrderLine.Item__c = itemCode;
        salesOrderLine.Quantity__c = quantity;
        salesOrderLine.Price__c = price;
        insert salesOrderLine;
        return salesOrderLine;
    }

}