source/objects/Entitlement_Template__c/Entitlement_Template__c.object-meta.xml
<CustomObject>
    <label>Entitlement Template</label>
    <nameField>
        <label>Entitlement Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Entitlement_Template__c/fields/Entitlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Type__c</fullName>
    <label>Entitlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>User Licenses</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Entitlement_Template__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <defaultValue>12</defaultValue>
    <description>Entitlement Period</description>
    <inlineHelpText>Period of the Entitlement in Months</inlineHelpText>
    <label>Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/objects/Entitlement_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entitlement Templates</relationshipLabel>
    <relationshipName>Entitlement_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Entitlement_Template__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>If Use Template Quantity is checked value from this field will be used as Entitlement Quantity.</description>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

source/objects/Entitlement_Template__c/fields/Use_Template_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Use_Template_Quantity__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use Template Quantity for Entitlement Quantity</description>
    <inlineHelpText>Use Template Quantity for Entitlement Quantity</inlineHelpText>
    <label>Use Template Quantity</label>
    <type>Checkbox</type>
</CustomField>

source/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Sales_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N40000001jWqAEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Sales_Order__c/fields/Service_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract_Id__c</fullName>
    <label>Service Contract Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

source/objects/Sales_Order__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

source/objects/Sales_Order__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

source/objects/Sales_Order_Item__c/Sales_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Line items for Sales Order document.</description>
    <label>Sales Order Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/objects/Sales_Order_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

source/objects/Sales_Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

source/objects/Sales_Order_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipName>R00N40000001jWpEEAU</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/classes/SalesOrderUtils.cls
/*
 * File Name    : SalesOrderUtils.cls
 * Description  : Global Apex Class to manage Sales Order events.
 * 
 * Modification Log
================================================================================
 * Ver    Date              	Author                Modification
--------------------------------------------------------------------------------
 * 1.0    12/19/2014         	Bluescape
 * 
*/

global class SalesOrderUtils {

	webservice static String createServiceContract(Id salesOrderId) {
		try {
			
			List<ServiceContract> serviceContracts = [select Id from ServiceContract where Sales_Order__c = :salesOrderId];
			if (serviceContracts.size() > 0) {
				return 'Error: Service Contract already exist for this Sales Order, can not create new Service Contract';
			}
			
			// Using Standard Price Book as per discussion with Justus
			List<Pricebook2> pricebooks = [select Id, Name, IsActive, IsStandard, Description 
							from Pricebook2 where IsStandard = true and Name = 'Standard Price Book'];

			if (pricebooks.size() <= 0) {
				return 'Error: Standard Price Book not setup correctly, can not create new Service Contract';
			}
				
			Sales_Order__c salesOrder = [select Id, 
											Name, 
											Account__c, 
											Account__r.BillingStreet, Account__r.BillingCity, Account__r.BillingState, Account__r.BillingPostalCode, Account__r.BillingCountry, 
											Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, Account__r.ShippingCountry, 
											Subtotal__c, 
											Service_Contract_Id__c, 
											Total__c 
										from Sales_Order__c 
										where Id = :salesOrderId];
			Account account = [select Id from Account where Id = :salesOrder.Account__c];
			ServiceContract serviceContract = new ServiceContract();
			serviceContract.Name = salesOrder.Name;
			serviceContract.Sales_Order__c = salesOrder.Id;
			serviceContract.Pricebook2Id = pricebooks[0].Id;
			serviceContract.AccountId = salesOrder.Account__c;
			serviceContract.Account = account;
/*			
			serviceContract.BillingStreet = salesOrder.Account__r.BillingStreet;
			serviceContract.BillingCity = salesOrder.Account__r.BillingCity;
			serviceContract.BillingState = salesOrder.Account__r.BillingState;
			serviceContract.BillingPostalCode = salesOrder.Account__r.BillingPostalCode;
			serviceContract.BillingCountry = salesOrder.Account__r.BillingCountry;
			serviceContract.ShippingStreet = salesOrder.Account__r.ShippingStreet;
			serviceContract.ShippingCity = salesOrder.Account__r.ShippingCity;
			serviceContract.ShippingState = salesOrder.Account__r.ShippingState;
			serviceContract.ShippingPostalCode = salesOrder.Account__r.ShippingPostalCode;
			serviceContract.ShippingCountry = salesOrder.Account__r.ShippingCountry;
*/			
			insert serviceContract;

			salesOrder.Service_Contract_Id__c = serviceContract.Id;
			update salesOrder;
			
			List<Sales_Order_Item__c> salesOrderItems = [select Item__c, 
											Description__c, 
											Quantity__c, 
											Price__c 
										from Sales_Order_Item__c 
										where Sales_Order__c = :salesOrderId];

			if (salesOrderItems.size() <= 0) {
				return serviceContract.Name;
			}
			String debugString = '\n\n\n ----------- Bluescape SalesOrderUtils.createServiceContract ------------ \n';
			Set<String> productIdSet = new Set<String>();
			Map<String, Id> productCode2PricebookEntryIdMap = new Map<String, Id>();
			Map<Id, Id> pricebookEntryId2ProductIdMap = new Map<Id, Id>();
			List<PricebookEntry> pricebookEntries = [select Id, Product2Id, ProductCode, UnitPrice, IsActive
															from PricebookEntry
															where Pricebook2Id = :pricebooks[0].Id
															order by ProductCode ];
			for (PricebookEntry pricebookEntry : pricebookEntries) {
				productCode2PricebookEntryIdMap.put(pricebookEntry.ProductCode, pricebookEntry.Id);
				pricebookEntryId2ProductIdMap.put(pricebookEntry.Id, pricebookEntry.Product2Id);
				productIdSet.add(pricebookEntry.Product2Id);
			}

			List<Entitlement_Template__c> entitlementTemplates = [select Id, Name, Entitlement_Type__c, 
																	Product__c, Use_Template_Quantity__c, Quantity__c, Period__c 
																from Entitlement_Template__c 
																where Product__c IN :productIdSet];
			debugString = debugString + '\tentitlementTemplates.size : ' + entitlementTemplates.Size() + '\n';
			debugString = debugString + '\tproductIdSet : ' + productIdSet + '\n';
			debugString = debugString + '\n-----------------------------------------------------------\n\n';
			System.debug(debugString);
			Map<Id, List<Entitlement_Template__c>> entitlementTemplateMap = new Map<Id, List<Entitlement_Template__c>>();
			for (Entitlement_Template__c entitlementTemplate : entitlementTemplates) {
				List<Entitlement_Template__c> entitlementTemplateList = entitlementTemplateMap.get(entitlementTemplate.Product__c);
				if (entitlementTemplateList == null) {
					entitlementTemplateList = new List<Entitlement_Template__c>();
				}
				entitlementTemplateList.add(entitlementTemplate);
				entitlementTemplateMap.put(entitlementTemplate.Product__c, entitlementTemplateList);
			}

			List<ContractLineItem> newContractLineItemList = new List<ContractLineItem>();
			for (Sales_Order_Item__c salesOrderItem : salesOrderItems) {
				Id pricebookEntryId = productCode2PricebookEntryIdMap.get(salesOrderItem.Item__c);
				if (pricebookEntryId == null) {
					// Sales Order line item has wrong product code, can not create contract line item
					continue;
				}
				ContractLineItem contractLineItem = new ContractLineItem();
				contractLineItem.ServiceContractId = serviceContract.Id;
				contractLineItem.PricebookEntryId = pricebookEntryId;
				contractLineItem.Description = salesOrderItem.Description__c;
				contractLineItem.Quantity = salesOrderItem.Quantity__c;
				contractLineItem.UnitPrice = salesOrderItem.Price__c;
				newContractLineItemList.add(contractLineItem);
			}
			if (newContractLineItemList.size() > 0) {
				insert newContractLineItemList;
			}
			
			List<Entitlement> entitlementList = new List<Entitlement>();
			for (ContractLineItem contractLineItem : newContractLineItemList) {
				Id productId = pricebookEntryId2ProductIdMap.get(contractLineItem.PricebookEntryId);
				List<Entitlement_Template__c> entitlementTemplateList = entitlementTemplateMap.get(productId);
				if (entitlementTemplateList != null && entitlementTemplateList.size() > 0) {
					for (Entitlement_Template__c entitlementTemplate : entitlementTemplateList) {
						if (entitlementTemplate.Use_Template_Quantity__c) {
							for (Integer q = 0; q < contractLineItem.Quantity; q++) {
								Entitlement entitlement = new Entitlement();
								entitlement.Name = entitlementTemplate.Name;
								entitlement.AccountId = serviceContract.Account.Id;
								// entitlement.AssetId = serviceContract.Account;
								entitlement.ContractLineItemId = contractLineItem.Id;
								entitlement.Type = entitlementTemplate.Entitlement_Type__c;
								entitlement.ServiceContractId = serviceContract.Id;
								entitlement.Quantity__c = entitlementTemplate.Quantity__c;
                                entitlement.Period__c = entitlementTemplate.Period__c;
								entitlementList.add(entitlement);
								
							}
						} else {
							Entitlement entitlement = new Entitlement();
							entitlement.Name = entitlementTemplate.Name;
							entitlement.AccountId = serviceContract.Account.Id;
							// entitlement.AssetId = serviceContract.Account;
							entitlement.ContractLineItemId = contractLineItem.Id;
							entitlement.Type = entitlementTemplate.Entitlement_Type__c;
							entitlement.ServiceContractId = serviceContract.Id;
							entitlement.Quantity__c = contractLineItem.Quantity;
                            entitlement.Period__c = entitlementTemplate.Period__c;
							entitlementList.add(entitlement);
						}
					}
				}
			}
			if (entitlementList.size() > 0) {
				insert entitlementList;
			}
			
			return serviceContract.Name;
		} catch (Exception e) {
			return e.getMessage();
		}
	}
}