source/objects/Bluescape_API_Token__c/Bluescape_API_Token__c.object-meta.xml
<CustomObject>
    <label>Bluescape API Token</label>
    <nameField>
        <label>Bluescape API Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_API_Token__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <label>Expires At</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Redirect_URI__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URI__c</fullName>
    <label>Redirect URI</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/classes/LeadIntegrationAdminTest.cls
@isTest
public class LeadIntegrationAdminTest {
    
	@isTest
    public static void testAdminCreationCallouts() {
        Bluescape_API_Token__c bluescapeAPIToken = new Bluescape_API_Token__c(
                Name = 'Bluescape_Api_Integration',
                Access_Token__c = 'accessToken',
                Client_ID__c = '123',
                Client_Secret__c = '123',
                Expires_At__c = 2000000000,
                Redirect_URI__c = 'https://localhost/callback',
                Refresh_Token__c = '123'
        );
        insert bluescapeAPIToken;
        
        Lead lead = new Lead(
                FirstName = 'Test',
                LastName = 'Lead',
                Email = 'test@gmail.com',
                Company = 'test',
                Free_Trial__c = false,
                Org_Id__c = '4141'
        );
        insert lead;
        
        Test.startTest();
        LeadIntegrationAdmin.configureOrgWithoutAdmin(new List<Id>{lead.Id});
        Test.stopTest();
    }
}