source/objects/Bluescape_API_Token__c/Bluescape_API_Token__c.object-meta.xml
<CustomObject>
    <label>Bluescape API Token</label>
    <nameField>
        <label>Bluescape API Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_API_Token__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <label>Expires At</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Redirect_URI__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URI__c</fullName>
    <label>Redirect URI</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_Org__c/Bluescape_Org__c.object-meta.xml
<CustomObject>
    <description>Bluescape Portal Organization</description>
    <label>Bluescape Org</label>
    <nameField>
        <label>Bluescape Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Org__c/fields/Bluescape_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org_ID__c</fullName>
    <externalId>true</externalId>
    <label>Bluescape Org ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

source/objects/ContactBluescapeOrg__c/ContactBluescapeOrg__c.object-meta.xml
<CustomObject>
    <description>The many to many association between Portal Users (Contacts flaged as Portal Users) and Bluescape Org&#39;s</description>
    <label>ContactBluescapeOrg</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ContactBluescapeOrg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ContactBluescapeOrgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/objects/ContactBluescapeOrg__c/fields/Bluescape_Org__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org__c</fullName>
    <label>Bluescape Org</label>
    <referenceTo>Bluescape_Org__c</referenceTo>
    <relationshipLabel>Portal Users</relationshipLabel>
    <relationshipName>ContactBluescapeOrgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/objects/ContactBluescapeOrg__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bluescape Orgs</relationshipLabel>
    <relationshipName>ContactBluescapeOrgs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/objects/ContactBluescapeOrg__c/fields/Extension_Duration__c.field-meta.xml
<CustomField>
    <fullName>Extension_Duration__c</fullName>
    <label>Extension Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Extension_Duration</valueSetName>
    </valueSet>
</CustomField>

source/objects/ContactBluescapeOrg__c/fields/Trial_Extended__c.field-meta.xml
<CustomField>
    <fullName>Trial_Extended__c</fullName>
    <label>Trial Extended</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trial_Extended</valueSetName>
    </valueSet>
</CustomField>

source/classes/BluescapeExtendingOrgExpirationTest.cls
@isTest
public class BluescapeExtendingOrgExpirationTest {
    
    @TestSetup
    public static void setup() {
        Bluescape_API_Token__c bluescapeAPIToken = new Bluescape_API_Token__c(
                Name = 'Bluescape_Api_Integration',
                Access_Token__c = 'accessToken',
                Client_ID__c = '123',
                Client_Secret__c = '123',
                Expires_At__c = 2000000000,
                Redirect_URI__c = 'https://localhost/callback',
                Refresh_Token__c = '123'
        );
        insert bluescapeAPIToken;
    }
    
    @isTest
    public static void testExtendingOrgExpiration() {
        Lead lead = new Lead(
            LastName = 'Test',
            Company = 'Test',
            Org_Id__c = '123',
            Extension_Duration__c = '7'
        );
        insert lead;
        
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationExtendingOrgExpMock());
        
        Test.startTest();
        BluescapeExtendingOrgExpiration.extendingOrgExpiration(new List<Id>{lead.Id});
        Test.stopTest();
        
        System.assertEquals('Success', [SELECT Trial_Extended__c FROM Lead WHERE Id = :lead.Id].Trial_Extended__c);
    }
    
    @isTest
    public static void testExtendingOrgExpirationFail() {
        Lead lead = new Lead(
            LastName = 'Test',
            Company = 'Test',
            Org_Id__c = '123',
            Extension_Duration__c = '7'
        );
        insert lead;
        
        UtilIntegration.setFailingMock = true;
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationExtendingOrgExpMock());
        
        Test.startTest();
        BluescapeExtendingOrgExpiration.extendingOrgExpiration(new List<Id>{lead.Id});
        Test.stopTest();
        
        System.assertEquals('Fail', [SELECT Trial_Extended__c FROM Lead WHERE Id = :lead.Id].Trial_Extended__c);
    }
    
    @isTest
    public static void testExtendingOrgExpirationForContactBluescapeOrgObject() {
        Contact contact = new Contact(
                LastName = 'Contact',
                Email = 'contact@email.com'
        );
        insert contact;
        
        Bluescape_Org__c bluescapeOrg = new Bluescape_Org__c(
            Bluescape_Org_ID__c = 123            
        );
        insert bluescapeOrg;
        
        ContactBluescapeOrg__c contactBluescapeOrg = new ContactBluescapeOrg__c(
            Contact__c = contact.Id,
            Bluescape_Org__c = bluescapeOrg.Id,
            Extension_Duration__c = '7'
        );
        insert contactBluescapeOrg;
        
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationExtendingOrgExpMock());
        
        Test.startTest();
        BluescapeExtendingOrgExpiration.extendingOrgExpiration(new List<Id>{contactBluescapeOrg.Id});
        Test.stopTest();
        
        System.assertEquals('Success', [SELECT Trial_Extended__c FROM ContactBluescapeOrg__c WHERE Id = :contactBluescapeOrg.Id].Trial_Extended__c);
    }
}