source/objects/Bluescape_API_Token__c/Bluescape_API_Token__c.object-meta.xml
<CustomObject>
    <label>Bluescape API Token</label>
    <nameField>
        <label>Bluescape API Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_API_Token__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <label>Expires At</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Redirect_URI__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URI__c</fullName>
    <label>Redirect URI</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_Demo__c/Bluescape_Demo__c.object-meta.xml
<CustomObject>
    <description>External Bluescape Events, including Demo Installation requests</description>
    <label>Bluescape Demo</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bluescape Demos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Demo__c/fields/Demo_Duration__c.field-meta.xml
<CustomField>
    <fullName>Demo_Duration__c</fullName>
    <label>Demo Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>7 days</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 days</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 days</label>
            </value>
            <value>
                <fullName>90</fullName>
                <label>90 days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity associated with this demo installation request</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <label>Org ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who to contact for scheduling shipping, installation and removal of the demo unit</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Bluescape_Org__c/Bluescape_Org__c.object-meta.xml
<CustomObject>
    <description>Bluescape Portal Organization</description>
    <label>Bluescape Org</label>
    <nameField>
        <label>Bluescape Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Org__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bluescape Orgs</relationshipLabel>
    <relationshipName>Bluescape_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/ContactBluescapeOrg__c/ContactBluescapeOrg__c.object-meta.xml
<CustomObject>
    <description>The many to many association between Portal Users (Contacts flaged as Portal Users) and Bluescape Org&#39;s</description>
    <label>ContactBluescapeOrg</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ContactBluescapeOrg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ContactBluescapeOrgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/objects/ContactBluescapeOrg__c/fields/Bluescape_Org__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org__c</fullName>
    <label>Bluescape Org</label>
    <referenceTo>Bluescape_Org__c</referenceTo>
    <relationshipLabel>Portal Users</relationshipLabel>
    <relationshipName>ContactBluescapeOrgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/objects/ContactBluescapeOrg__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bluescape Orgs</relationshipLabel>
    <relationshipName>ContactBluescapeOrgs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Sales_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N40000001jWqAEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Sales_Order__c/fields/Bluescape_Org_Date__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org_Date__c</fullName>
    <description>The date when we should invoice/rev rec on licenses</description>
    <inlineHelpText>The date when the client gets access to the Bluescape Org/User Licenses (for new customers) or contract sign/closed date (for existing customers) whichever is later</inlineHelpText>
    <label>Bluescape Org Date</label>
    <type>Date</type>
</CustomField>

source/objects/Sales_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>R00N40000001jWqUEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Sales_Order__c/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

source/objects/Sales_Order__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

source/classes/UtilIntegrationTest.cls
@isTest
public class UtilIntegrationTest {

	@TestSetup
	public static void setup() {
		Account account = new Account(
				Name = 'Test Account',
				Type = 'Prospect',
				Pod__c = 'Central'
		);
		insert account;

		Contact contact = new Contact(
				LastName = 'Contact',
				Email = 'contact@email.com',
				AccountId = account.Id
		);
		insert contact;

		Opportunity opp = new Opportunity(
				Name = 'Test',
				AccountId = account.Id,
				StageName = '0-Pre-Opportunity',
				CloseDate = Date.today(),
				LeadSource = 'Direct traffic',
				Type = 'New Business'
		);
		insert opp;

		Lead lead = new Lead(
				FirstName = 'Test',
				LastName = 'Lead',
				Email = 'test@gmail.com',
				Company = 'test',
				Free_Trial__c = false
		);
		insert lead;

		Bluescape_API_Token__c bluescapeAPIToken = new Bluescape_API_Token__c(
				Name = 'Bluescape_Api_Integration',
				Access_Token__c = 'accessToken',
				Client_ID__c = '123',
				Client_Secret__c = '123',
				Expires_At__c = 2000000000,
				Redirect_URI__c = 'https://localhost/callback',
				Refresh_Token__c = '123'
		);
		insert bluescapeAPIToken;
	}

	@isTest
	public static void testLeadIntegrationAllCalloutsSuccessMock() {
		Lead lead = [SELECT Id, Email, Owner.Email FROM Lead LIMIT 1];

		Test.startTest();
		BluescapeOrgRequest.configureBluescapeOrg(new List<Id>{lead.Id});
		Test.stopTest();

		Lead leadAfterInsert = [SELECT Org_Id__c FROM Lead WHERE Id = :lead.Id];
		System.assertNotEquals(null, leadAfterInsert.Org_Id__c);

		UtilIntegration.getErrorEmailAddress();
	}

	@isTest
	public static void testContactIntegrationAllCalloutsSuccessMock() {
		Account account = [SELECT Id FROM Account LIMIT 1];
		Contact contact = [SELECT Id FROM Contact LIMIT 1];

		Test.startTest();
		BluescapeOrgRequest.configureBluescapeOrg(new List<Id>{contact.Id});
		Test.stopTest();

		Bluescape_Org__c bluescapeOrg = [SELECT Name, Account__c FROM Bluescape_Org__c];
		ContactBluescapeOrg__c contactBluescapeOrg = [SELECT Bluescape_Org__c, Contact__c FROM ContactBluescapeOrg__c];

		System.assertEquals(account.Id, bluescapeOrg.Account__c);
		System.assertEquals(contact.Id, contactBluescapeOrg.Contact__c);
		System.assertEquals(bluescapeOrg.Id, contactBluescapeOrg.Bluescape_Org__c);
	}

	@isTest
	public static void testBluescapeDemoIntegrationAllCalloutsSuccessMock() {
		Contact contact = [SELECT Id FROM Contact LIMIT 1];
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

		Test.startTest();
		Bluescape_Demo__c bluescapeDemo = new Bluescape_Demo__c(
				Primary_Contact__c = contact.Id,
				Opportunity__c = opp.Id,
				Demo_Duration__c = '7'
		);
		insert bluescapeDemo;
		Test.stopTest();

		Bluescape_Demo__c bluescapeDemoAfterInsert = [
				SELECT
					Org_Id__c, Opportunity__r.Org_Id__c
				FROM
					Bluescape_Demo__c
				WHERE
					Id = :bluescapeDemo.Id
		];
		System.assertNotEquals(null, bluescapeDemoAfterInsert.Org_Id__c);
		System.assertNotEquals(null, bluescapeDemoAfterInsert.Opportunity__r.Org_Id__c);
	}

	@isTest
	public static void testSalesOrderIntegrationAllCalloutsSuccessMock() {
		Contact contact = [SELECT Id FROM Contact LIMIT 1];
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

		OpportunityContactRole oppContacRole = new OpportunityContactRole(
				OpportunityId = opp.Id,
				ContactId = contact.Id,
				IsPrimary = true
		);
		insert oppContacRole;

		Test.startTest();
		Sales_Order__c salesOrder = new Sales_Order__c(
				Name = 'test',
				Opportunity__c = opp.Id
		);
		insert salesOrder;
		Test.stopTest();

		Sales_Order__c salesOrderAfterInsert = [
				SELECT
					Org_Id__c, Primary_Contact__c, Bluescape_Org_Date__c
				FROM
					Sales_Order__c
				WHERE
					Id = :salesOrder.Id
		];

		System.assertNotEquals(null, salesOrderAfterInsert.Org_Id__c);
		System.assertEquals(contact.Id, salesOrderAfterInsert.Primary_Contact__c);
		System.assertEquals(Date.today(), salesOrderAfterInsert.Bluescape_Org_Date__c);
	}

	@isTest
	public static void testCreateOrgByLeadFailureMock() {
		Lead lead = [SELECT Id, Email, Owner.Email FROM Lead LIMIT 1];

		UtilIntegration.setFailingMock = true;
		UtilIntegration.sObjectType = 'Lead';
		UtilIntegration.lead = lead;
		UtilIntegration.recordId = lead.Id;

		Test.startTest();
		UtilIntegration.createOrg();
		Test.stopTest();
	}

	@isTest
	public static void testCreateOrgByContactFailureMock() {
		Contact contact = [SELECT Id, Email, Owner.Email FROM contact LIMIT 1];

		UtilIntegration.setFailingMock = true;
		UtilIntegration.sObjectType = 'Contact';
		UtilIntegration.contact = contact;
		UtilIntegration.recordId = contact.Id;

		Test.startTest();
		UtilIntegration.createOrg();
		Test.stopTest();
	}

	@isTest
	public static void testCreateOrgByBluescapeDemoFailureMock() {
		Contact contact = [SELECT Id FROM Contact LIMIT 1];
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		Bluescape_Demo__c bluescapeDemo = new Bluescape_Demo__c(
				Primary_Contact__c = contact.Id,
				Opportunity__c = opp.Id,
				Demo_Duration__c = '7'
		);
		insert bluescapeDemo;

		Test.startTest();
		UtilIntegration.setFailingMock = true;
		UtilIntegration.sObjectType = 'Bluescape_Demo__c';
		UtilIntegration.bluescapeDemo = bluescapeDemo;
		UtilIntegration.recordId = bluescapeDemo.Id;

		UtilIntegration.createOrg();
		Test.stopTest();
	}

	@isTest
	public static void testCreateExternalUserFailureMock() {
		Lead lead = [SELECT Id, Email, Owner.Email FROM Lead LIMIT 1];

		UtilIntegration.setFailingMock = true;
		UtilIntegration.orgId = 123;
		UtilIntegration.sObjectType = 'Lead';
		UtilIntegration.lead = lead;
		UtilIntegration.recordId = lead.Id;
		UtilIntegration.qtyOfGetWSIdRequests = 0;

		Test.startTest();
		UtilIntegration.createExternalUser();
		Test.stopTest();
	}

	@isTest
	public static void testCopyWorkspaceFailureMock() {
		Lead lead = [SELECT Id, Email, Owner.Email FROM Lead LIMIT 1];

		UtilIntegration.setFailingMock = true;
		UtilIntegration.workspaceName = 'test';
		UtilIntegration.orgId = 123;
		UtilIntegration.sObjectType = 'Lead';
		UtilIntegration.lead = lead;
		UtilIntegration.recordId = lead.Id;
		UtilIntegration.qtyOfGetWSIdRequests = 0;

		Test.startTest();
		UtilIntegration.copyWorkspace();
		Test.stopTest();
	}

	@isTest
	public static void testGetCopiedWorkspaceIdFailureMock() {
		Lead lead = [SELECT Id, Email, Owner.Email FROM Lead LIMIT 1];

		UtilIntegration.setFailingMock = true;
		UtilIntegration.workspaceName = 'test';
		UtilIntegration.orgId = 123;
		UtilIntegration.sObjectType = 'Lead';
		UtilIntegration.lead = lead;
		UtilIntegration.recordId = lead.Id;
		UtilIntegration.qtyOfGetWSIdRequests = 0;

		Test.startTest();
		UtilIntegration.getCopiedWorkspaceId();
		Test.stopTest();
	}

	@isTest
	public static void testMoveWorkspaceToOrgFailureMock() {
		Lead lead = [SELECT Id, Email, Owner.Email FROM Lead LIMIT 1];

		UtilIntegration.setFailingMock = true;
		UtilIntegration.workspaceName = 'test';
		UtilIntegration.orgId = 123;
		UtilIntegration.workspaceId = 123;
		UtilIntegration.sObjectType = 'Lead';
		UtilIntegration.lead = lead;
		UtilIntegration.recordId = lead.Id;
		UtilIntegration.qtyOfGetWSIdRequests = 0;

		Test.startTest();
		UtilIntegration.moveWorkspaceToOrg();
		Test.stopTest();
	}

	@isTest
	public static void testMakeWorkspacePublicFailureMock() {
		Lead lead = [SELECT Id, Email, Owner.Email FROM Lead LIMIT 1];

		UtilIntegration.setFailingMock = true;
		UtilIntegration.workspaceName = 'test';
		UtilIntegration.orgId = 123;
		UtilIntegration.workspaceId = 123;
		UtilIntegration.sObjectType = 'Lead';
		UtilIntegration.lead = lead;
		UtilIntegration.recordId = lead.Id;
		UtilIntegration.qtyOfGetWSIdRequests = 0;

		Test.startTest();
		UtilIntegration.makeWorkspacePublic();
		Test.stopTest();
	}

	@isTest
	public static void testCreateExtraAdminUserInBluescape() {
		Lead lead = [SELECT Id FROM Lead LIMIT 1];

		Test.startTest();
		UtilIntegration.createExtraAdminUserInBluescape(1, lead.Id);
		Test.stopTest();

		Lead leadAfterCreateAdminUser = [SELECT Sales_Resource__c FROM Lead WHERE Id = :lead.Id];
		System.assertEquals(UserInfo.getUserId(), leadAfterCreateAdminUser.Sales_Resource__c);
	}

	@isTest
	public static void testCreateExtraAdminUserInBluescapeFailureMock() {
		UtilIntegration.setFailingMock = true;
		Boolean failed;
		Lead lead = [SELECT Id FROM Lead LIMIT 1];

		Test.startTest();
		try {
			UtilIntegration.createExtraAdminUserInBluescape(1, lead.Id);
		} catch (Exception e) {
			failed = true;
		}
		Test.stopTest();

		System.assert(failed);

		Lead leadAfterCreateAdminUser = [SELECT Sales_Resource__c FROM Lead WHERE Id = :lead.Id];
		System.assertEquals(null, leadAfterCreateAdminUser.Sales_Resource__c);
	}
}