source/objects/Bluescape_API_Token__c/Bluescape_API_Token__c.object-meta.xml
<CustomObject>
    <label>Bluescape API Token</label>
    <nameField>
        <label>Bluescape API Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_API_Token__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <label>Expires At</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Redirect_URI__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URI__c</fullName>
    <label>Redirect URI</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_Demo__c/Bluescape_Demo__c.object-meta.xml
<CustomObject>
    <description>External Bluescape Events, including Demo Installation requests</description>
    <label>Bluescape Demo</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bluescape Demos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Demo__c/fields/Created_Admin_User_For_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Created_Admin_User_For_Primary_Contact__c</fullName>
    <label>Admin User For Primary Contact Created</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Demo_Duration__c.field-meta.xml
<CustomField>
    <fullName>Demo_Duration__c</fullName>
    <label>Demo Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>7 days</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 days</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 days</label>
            </value>
            <value>
                <fullName>90</fullName>
                <label>90 days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity associated with this demo installation request</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who to contact for scheduling shipping, installation and removal of the demo unit</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

source/classes/BluescapeDemoPrimaryContactAdminUserTest.cls
@isTest
public class BluescapeDemoPrimaryContactAdminUserTest {

	@isTest
	public static void testBluescapeDemoPrimaryContactAdminUser() {
		Bluescape_API_Token__c bluescapeAPIToken = new Bluescape_API_Token__c(
				Name = 'Bluescape_Api_Integration',
				Access_Token__c = 'accessToken',
				Client_ID__c = '123',
				Client_Secret__c = '123',
				Expires_At__c = 2000000000,
				Redirect_URI__c = 'https://localhost/callback',
				Refresh_Token__c = '123'
		);
		insert bluescapeAPIToken;

		Account account = new Account(
				Name = 'Test Account',
				Type = 'Prospect',
				Pod__c = 'Central'
		);
		insert account;

		Contact contact = new Contact(
				LastName = 'Contact',
				Email = 'contact@email.com',
				AccountId = account.Id
		);
		insert contact;

		Opportunity opp = new Opportunity(
				Name = 'Test',
				AccountId = account.Id,
				StageName = '0-Pre-Opportunity',
				CloseDate = Date.today(),
				LeadSource = 'Direct traffic'
		);
		insert opp;

		Bluescape_Demo__c bluescapeDemo = new Bluescape_Demo__c(
				Primary_Contact__c = contact.Id,
				Opportunity__c = opp.Id,
				Demo_Duration__c = '7'
		);
		insert bluescapeDemo;

		Test.startTest();
		BluescapeDemoPrimaryContactAdminUser.createAdminUser(new List<Id>{bluescapeDemo.Id});
		Test.stopTest();

		Bluescape_Demo__c bluescapeDemoAfterCreateAdminUserInBS = [
				SELECT
					Created_Admin_User_For_Primary_Contact__c
				FROM
					Bluescape_Demo__c
				WHERE
					Id = :bluescapeDemo.Id LIMIT 1
		];
		System.assertEquals('Success', bluescapeDemoAfterCreateAdminUserInBS.Created_Admin_User_For_Primary_Contact__c);
	}
}