source/objects/Bluescape_API_Token__c/Bluescape_API_Token__c.object-meta.xml
<CustomObject>
    <label>Bluescape API Token</label>
    <nameField>
        <label>Bluescape API Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_API_Token__c/fields/Error_Email__c.field-meta.xml
<CustomField>
    <fullName>Error_Email__c</fullName>
    <label>Error Email</label>
    <type>Email</type>
</CustomField>

source/objects/Bluescape_Demo__c/Bluescape_Demo__c.object-meta.xml
<CustomObject>
    <description>External Bluescape Events, including Demo Installation requests</description>
    <label>Bluescape Demo</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bluescape Demos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Demo__c/fields/Created_Admin_User_For_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Created_Admin_User_For_Primary_Contact__c</fullName>
    <label>Admin User For Primary Contact Created</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Demo_Duration__c.field-meta.xml
<CustomField>
    <fullName>Demo_Duration__c</fullName>
    <label>Demo Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <label>7 days</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 days</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 days</label>
            </value>
            <value>
                <fullName>90</fullName>
                <label>90 days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity associated with this demo installation request</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Org_Created__c.field-meta.xml
<CustomField>
    <fullName>Org_Created__c</fullName>
    <label>Org Created</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bluescape_Integration_Status</valueSetName>
    </valueSet>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <label>Org ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who to contact for scheduling shipping, installation and removal of the demo unit</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Bluescape_Demo__c/fields/Qty_of_Request__c.field-meta.xml
<CustomField>
    <fullName>Qty_of_Request__c</fullName>
    <label>Qty of Request</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/objects/Bluescape_Org__c/Bluescape_Org__c.object-meta.xml
<CustomObject>
    <description>Bluescape Portal Organization</description>
    <label>Bluescape Org</label>
    <nameField>
        <label>Bluescape Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_Org__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bluescape Orgs</relationshipLabel>
    <relationshipName>Bluescape_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Bluescape_Org__c/fields/Bluescape_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org_ID__c</fullName>
    <externalId>true</externalId>
    <label>Bluescape Org ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

source/objects/Bluescape_Org__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Org Plan Type</description>
    <label>Plan</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_Org__c/fields/Portal_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Portal_Created_Date__c</fullName>
    <description>Date when the Bluescape Org was created on the Portal</description>
    <inlineHelpText>Date when the Bluescape Org was created on the Portal</inlineHelpText>
    <label>Portal Created Date</label>
    <type>DateTime</type>
</CustomField>

source/objects/ContactBluescapeOrg__c/ContactBluescapeOrg__c.object-meta.xml
<CustomObject>
    <description>The many to many association between Portal Users (Contacts flaged as Portal Users) and Bluescape Org&#39;s</description>
    <label>ContactBluescapeOrg</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ContactBluescapeOrg Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ContactBluescapeOrgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

source/objects/ContactBluescapeOrg__c/fields/Bluescape_Org__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org__c</fullName>
    <label>Bluescape Org</label>
    <referenceTo>Bluescape_Org__c</referenceTo>
    <relationshipLabel>Portal Users</relationshipLabel>
    <relationshipName>ContactBluescapeOrgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/objects/ContactBluescapeOrg__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bluescape Orgs</relationshipLabel>
    <relationshipName>ContactBluescapeOrgs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

source/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Sales_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N40000001jWqAEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Sales_Order__c/fields/Bluescape_Org_Date__c.field-meta.xml
<CustomField>
    <fullName>Bluescape_Org_Date__c</fullName>
    <description>The date when we should invoice/rev rec on licenses</description>
    <inlineHelpText>The date when the client gets access to the Bluescape Org/User Licenses (for new customers) or contract sign/closed date (for existing customers) whichever is later</inlineHelpText>
    <label>Bluescape Org Date</label>
    <type>Date</type>
</CustomField>

source/objects/Sales_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>R00N40000001jWqUEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Sales_Order__c/fields/Org_Created__c.field-meta.xml
<CustomField>
    <fullName>Org_Created__c</fullName>
    <label>Org Created</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bluescape_Integration_Status</valueSetName>
    </valueSet>
</CustomField>

source/objects/Sales_Order__c/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

source/objects/Sales_Order__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

source/objects/Sales_Order__c/fields/Qty_of_Request__c.field-meta.xml
<CustomField>
    <fullName>Qty_of_Request__c</fullName>
    <label>Qty of Request</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/classes/UtilIntegration.cls
public class UtilIntegration {

	public static Boolean setFailingMock = false;
	public static Integer orgId;
	public static Integer workspaceId;
	public static Integer qtyOfGetWSIdRequests = 0;
	public static Contact contact;
	public static Contact salesOrderOpportunityPrimaryContact;
	public static Lead lead;
	public static Bluescape_Demo__c bluescapeDemo;
	public static Sales_Order__c salesOrder;
	public static String workspaceName;
	public static Bluescape_API_Token__c bluescapeAPIInfo;
	public static String bluescapeExternalUserEmail;
	public static String bluescapeAdminUserEmail;
	public static Id recordId;
	public static String sObjectType;
	public static String htmlRecordUrl;
	public static String bluescapeDemoPrimaryContactEmail;
	public static String statusOfCreatingBluescapeDemoAdminUserForPrimContact;

	public static void configureOrgProcess(Id objectId) {
		recordId = objectId;
		sObjectType = String.valueOf(recordId.getSObjectType());
		String orgRootUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/';
		htmlRecordUrl = '<a href="' + orgRootUrl + recordId + '" target="_blank">' + orgRootUrl + recordId + '</a>';

		if (sObjectType == 'Contact') {
			contact = getContact();

			if (contact.Email == null) {
				System.debug('Contact must have populate Email field');
				return;
			}

			bluescapeExternalUserEmail = contact.Email;
			bluescapeAdminUserEmail = contact.Owner.Email;

		} else if (sObjectType == 'Lead') {
			lead = getLead();

			if (lead.Email == null) {
				System.debug('Lead must have populate Email field');
				return;
			}

			bluescapeExternalUserEmail = lead.Email;
			bluescapeAdminUserEmail = lead.Owner.Email;

		} else if (sObjectType == 'Bluescape_Demo__c') {
			bluescapeDemo = getBluescapeDemo();
			bluescapeDemoPrimaryContactEmail = bluescapeDemo.Primary_Contact__r.Email;

			bluescapeAdminUserEmail = bluescapeDemo.Owner.Email;

		} else if (sObjectType == 'Sales_Order__c') {
			salesOrder = getSalesOrder();

			List<OpportunityContactRole> oppPrimaryRole = [
					SELECT
						ContactId
					FROM
						OpportunityContactRole
					WHERE
						OpportunityId = :salesOrder.Opportunity__c AND IsPrimary = true LIMIT 1
			];

			if (oppPrimaryRole.isEmpty()) {
				System.debug('Opportunity does not has Primary Contact');
				return;
			}

			salesOrderOpportunityPrimaryContact = [
					SELECT
						Id, Email
					FROM
						Contact
					WHERE
						Id = :oppPrimaryRole[0].ContactId
			];

			if (salesOrderOpportunityPrimaryContact.Email == null) {
				System.debug('Primary Contact must have populate Email field');
				return;
			}

			bluescapeExternalUserEmail = salesOrderOpportunityPrimaryContact.Email;
			bluescapeAdminUserEmail = salesOrder.Owner.Email;
		}

		workspaceName = 'Getting Started with Your Free Trial [' + String.valueOf(Datetime.now()) + ']';

		orgId = createOrg();
		if (orgId == null) return;

		Boolean createAdminUserSuccess = createAdminUser(orgId, bluescapeAdminUserEmail, true);
		if (createAdminUserSuccess == false) return;

		if (bluescapeDemoPrimaryContactEmail != null) {
			Boolean createAdminUserForPrimContactSuccess = createAdminUser(orgId, bluescapeDemoPrimaryContactEmail, true);

			if (createAdminUserForPrimContactSuccess == false) {
				statusOfCreatingBluescapeDemoAdminUserForPrimContact = 'Fail';

				return;
			}
			statusOfCreatingBluescapeDemoAdminUserForPrimContact = 'Success';
		}

		if (bluescapeExternalUserEmail != null) {
			Boolean createExternalUserSuccess = createExternalUser();
			if (createExternalUserSuccess == false) return;
		}

		Boolean copyWorkspaceBooleanSuccess = copyWorkspace();
		if (copyWorkspaceBooleanSuccess == false) return;

		WorkspaceIdWrapper workspaceIdWrapper = getCopiedWorkspaceId();
		if (workspaceIdWrapper != null) {
			workspaceId = workspaceIdWrapper.workspaceId;
			qtyOfGetWSIdRequests = workspaceIdWrapper.qtyOfGetWSIdRequests;
		} else {
			return;
		}

		Boolean moveWorkspaceToOrgSuccess = moveWorkspaceToOrg();
		if (moveWorkspaceToOrgSuccess == false) return;

		Boolean makeWorkspacePublicSuccess = makeWorkspacePublic();
		if (makeWorkspacePublicSuccess == false) return;

		updateCurrentRecord('Yes - Success');
		updateBluescapeAPIInfo();
	}

	public static Integer createOrg() {
		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationRequestOrgMock());
			}

			Integer durationDays = 35;
			if (sObjectType == 'Bluescape_Demo__c' && bluescapeDemo.Demo_Duration__c != null) {
				durationDays = Integer.valueOf(bluescapeDemo.Demo_Duration__c);
			} else if (sObjectType == 'Sales_Order__c') {
				durationDays = 396;
			}

			String orgName;
			if (sObjectType == 'Bluescape_Demo__c') {
				orgName = 'Demo: ' + bluescapeDemo.Opportunity__r.Name;
			} else if (sObjectType == 'Sales_Order__c') {
				orgName = salesOrder.Account__r.Name;
			} else {
				orgName = 'Trial: ' + bluescapeExternalUserEmail;
			}

			return BluescapeIntegration.makeOrgRequest(orgName, durationDays).orgId;

		} catch (BluescapeIntegration.ResponseException e) {
			sendErrorEmail('Free Trial process failed', 'Create org process failed, retry please.', e.getMessage());

			updateBluescapeAPIInfo();

			String queryStr = 'SELECT Org_Created__c FROM ' + recordId.getSObjectType() + ' WHERE Id = :recordId';
			sObject sObj = Database.query(queryStr);
			sObj.put('Org_Created__c', 'No - Create New Org Failed');

			update sObj;

			return null;
		}
	}

	public static Boolean createAdminUser(Integer bluescapeOrgId, String email, Boolean updateRecord) {
		if (email == 'admin@bluescape.com' || (sObjectType != null && sObjectType == 'Lead' && lead.OwnerId.getSobjectType() != User.SObjectType)) {
			return true;
		}

		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationCreateUserMock());
			}
			BluescapeIntegration.createUserRequest(bluescapeOrgId, email);

			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationGetUserMock());
			}
			Integer userId = BluescapeIntegration.getUserForMakingAdminRequest(bluescapeOrgId, email).userId;

			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationMakeUserAdminMock());
			}
			BluescapeIntegration.makeUserAdminRequest(bluescapeOrgId, userId);

			return true;

		} catch (BluescapeIntegration.ResponseException e) {
			sendErrorEmail('Free Trial process failed', 'Create Admin user in new Org process failed.', e.getMessage());

			updateBluescapeAPIInfo();

			if (updateRecord) {
				updateCurrentRecord('No - Create Admin User Failed');
			}

			return false;
		}
	}

	public static Boolean createExternalUser() {
		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationCreateUserMock());
			}
			BluescapeIntegration.createUserRequest(orgId, bluescapeExternalUserEmail);

			return true;
		} catch (BluescapeIntegration.ResponseException e) {
			sendErrorEmail('Free Trial process failed', 'Create external user in new Org process failed, retry please.',
					e.getMessage());

			updateCurrentRecord('No - Create External User Failed');
			updateBluescapeAPIInfo();

			return false;
		}
	}

	public static Boolean copyWorkspace() {
		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationCopyWorkspaceMock());
			}
			BluescapeIntegration.copyWorkspaceRequest(workspaceName);

			return true;
		} catch (BluescapeIntegration.ResponseException e) {
			sendErrorEmail('Free Trial process failed', 'Copying Workspace process failed, retry please.', e.getMessage());

			updateCurrentRecord('No - Copying Workspace Failed');
			updateBluescapeAPIInfo();

			return false;
		}
	}

	public static WorkspaceIdWrapper getCopiedWorkspaceId() {
		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationGetWorkspaceMock());
			}

			//We need to wait some time after copying Workspace to get it Id, so we created a loop to set fake timeout (≈ 2 sec)
			for (Integer i = 1; i <= 20; i++) {
				try {
					//fake timeout (≈ 2 sec)
					Long startingTime = System.now().getTime();
					Integer delayInMilliseconds = 2000; // two seconds delay
					while (System.now().getTime() - startingTime < delayInMilliseconds) {
						// Do nothing until desired delay has passed
					}

					Integer workspaceId = BluescapeIntegration.getNewWorkspaceIdRequest(workspaceName).workspaceId;

					return new WorkspaceIdWrapper(workspaceId, i);
				} catch (ListException le) {
					System.debug('Copied workspace currently not available, please try later: ' + le.getMessage());
				}
			}

			return null;

		} catch (BluescapeIntegration.ResponseException e) {
			sendErrorEmail('Free Trial process failed', 'Get Workspace id process failed, retry please.', e.getMessage());

			updateCurrentRecord('No - Get Copied Workspace Id Failed');
			updateBluescapeAPIInfo();
			return null;
		}
	}

	public static Boolean moveWorkspaceToOrg() {
		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationMoveWorkspaceMock());
			}
			BluescapeIntegration.moveWorkspaceToOrgRequest(orgId, workspaceId);

			return true;
		} catch (BluescapeIntegration.ResponseException e) {
			sendErrorEmail('Free Trial process failed', 'Moving Workspace to Org process failed, retry please.', e.getMessage());

			updateCurrentRecord('No - Move Workspace To Org Failed');
			updateBluescapeAPIInfo();

			return false;
		}
	}

	public static Boolean makeWorkspacePublic() {
		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationPublicWorkspaceMock());
			}
			BluescapeIntegration.makeWorkspacePublic(workspaceId);

			return true;
		} catch (BluescapeIntegration.ResponseException e) {
			sendErrorEmail('Free Trial process failed', 'Get Workspace id process failed, retry please.', e.getMessage());

			updateCurrentRecord('No - Make Workspace Public Failed');
			updateBluescapeAPIInfo();

			return false;
		}
	}

	@AuraEnabled
	public static void createExtraAdminUserInBluescape(Integer orgId, Id recordId) {
		String currentUserEmail = UserInfo.getUserEmail();
		Id currentUserId = UserInfo.getUserId();

		try {
			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationCreateUserMock());
			}
			BluescapeIntegration.createUserRequest(orgId, currentUserEmail);

			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationGetUserMock());
			}
			Integer userId = BluescapeIntegration.getUserForMakingAdminRequest(orgId, currentUserEmail).userId;

			if (Test.isRunningTest()) {
				Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationMakeUserAdminMock());
			}
			BluescapeIntegration.makeUserAdminRequest(orgId, userId);

			updateBluescapeAPIInfo();

			String recordsObjectType = String.valueOf(recordId.getSObjectType());
			String queryStr = 'SELECT ' +
									'Sales_Resource__c  ' +
								' FROM ' +
									recordsObjectType +
								' WHERE ' +
									'Id = :recordId';

			sObject sObj = Database.query(queryStr);
			sObj.put('Sales_Resource__c', currentUserId);

			update sObj;

		} catch (BluescapeIntegration.ResponseException e) {
			updateBluescapeAPIInfo();

			throw new AuraHandledException(e.getMessage());
		}
	}

	public static void createBluescapeOrgRecord(Contact contact, Integer orgId) {
		Bluescape_Org__c bluescapeOrg = new Bluescape_Org__c(
				Name = contact.Account.Name,
				Account__c = contact.AccountId,
				Bluescape_Org_ID__c = orgId,
				Portal_Created_Date__c = date.today(),
				Plan__c = 'Enterprise'
		);
		insert bluescapeOrg;

		ContactBluescapeOrg__c ContactBluescapeOrg = new ContactBluescapeOrg__c(
				Bluescape_Org__c = bluescapeOrg.Id,
				Contact__c = contact.Id
		);
		insert ContactBluescapeOrg;
	}

	public static Contact getContact() {
		Contact c = [
				SELECT
					Id, Email, Owner.Email, AccountId, Account.Name, Org_Id__c, Qty_of_Request__c, Org_Created__c
				FROM
					Contact
				WHERE
					Id = :recordId
		];

		return c;
	}

	public static Lead getLead() {
		Lead lead = [
				SELECT
					Id, Org_Id__c, Email, Owner.Email, Qty_of_Request__c, Org_Created__c
				FROM
					Lead
				WHERE
					Id = :recordId
		];

		return lead;
	}

	public static Bluescape_Demo__c getBluescapeDemo() {
		Bluescape_Demo__c bluescapeDemo = [
				SELECT
					Org_Id__c, Owner.Email, Qty_of_Request__c, Org_Created__c, Demo_Duration__c,
					Primary_Contact__r.Email, Created_Admin_User_For_Primary_Contact__c, Opportunity__c,
					Opportunity__r.Name
				FROM
					Bluescape_Demo__c
				WHERE
					Id = :recordId
		];

		return bluescapeDemo;
	}

	public static Sales_Order__c getSalesOrder() {
		Sales_Order__c salesOrder = [
				SELECT
					Owner.Email, Opportunity__c, Account__r.Name
				FROM
					Sales_Order__c
				WHERE
					Id = :recordId
		];

		return salesOrder;
	}

	public static String getErrorEmailAddress() {
		Bluescape_API_Token__c bluescapeAPIInfo = [
				SELECT
					Error_Email__c
				FROM
					Bluescape_API_Token__c
				WHERE
					Name = 'Bluescape_Api_Integration' LIMIT 1
		];

		return bluescapeAPIInfo.Error_Email__c;
	}

	private static void updateCurrentRecord(String createStatus) {
		if (sObjectType == 'Contact') {
			createBluescapeOrgRecord(contact, orgId);
		}

		String queryStr = 'SELECT ' +
								'Org_Id__c, Org_Created__c, Qty_of_Request__c ' +
								(sObjectType == 'Bluescape_Demo__c' ? ', Created_Admin_User_For_Primary_Contact__c, Opportunity__c' : '') +
								(sObjectType == 'Sales_Order__c' ? ', Bluescape_Org_Date__c, Primary_Contact__c' : '') +
							' FROM ' +
								sObjectType +
							' WHERE ' +
								'Id = :recordId';

		sObject sObj = Database.query(queryStr);

		sObj.put('Org_Id__c', String.valueOf(orgId));
		sObj.put('Org_Created__c', createStatus);
		sObj.put('Qty_of_Request__c', qtyOfGetWSIdRequests);

		if (sObjectType == 'Sales_Order__c') {
			sObj.put('Bluescape_Org_Date__c', Date.today());
			sObj.put('Primary_Contact__c', salesOrderOpportunityPrimaryContact.Id);
		}

		if (sObjectType == 'Bluescape_Demo__c') {
			sObj.put('Created_Admin_User_For_Primary_Contact__c', statusOfCreatingBluescapeDemoAdminUserForPrimContact);

			if (statusOfCreatingBluescapeDemoAdminUserForPrimContact == 'Success') {
				Contact primaryContact = [
						SELECT
							Org_Id__c
						FROM
							Contact
						WHERE
							Id = :bluescapeDemo.Primary_Contact__c
				];

				if (primaryContact.Org_Id__c == null) {
					primaryContact.Org_Id__c = String.valueOf(orgId);
				} else {
					primaryContact.Org_Id__c += ', ' + String.valueOf(orgId);
				}

				update primaryContact;
			}
		}

		update sObj;

		if (sObjectType == 'Bluescape_Demo__c') {
			String opportunityId = String.valueOf(sObj.get('Opportunity__c'));
			Opportunity opportunity = [
					SELECT
						Org_Id__c
					FROM
						Opportunity
					WHERE
						Id = :opportunityId
			];
			opportunity.Org_Id__c = String.valueOf(orgId);

			update opportunity;
		}
	}

	public static void updateBluescapeAPIInfo() {
		if (bluescapeAPIInfo != null) {
			update bluescapeAPIInfo;
		}
	}

	public static void sendErrorEmail(String msgSubject, String msg, String errorMsg) {
		String msgHtmlBody = '<p>' + msg + '</p>';
		msgHtmlBody += '<p>' + errorMsg + '</p>' + '<p>' + htmlRecordUrl + '</p>';

		try {
			EmailManager.sendEmail(new List<String> {getErrorEmailAddress(), 'yaroslav.pazhukh@wiserspread.com'}, msgSubject, msgHtmlBody);
		} catch (Exception e) {
			System.debug(e);
		}
	}

	public class WorkspaceIdWrapper {
		Integer workspaceId;
		Integer qtyOfGetWSIdRequests;

		public WorkspaceIdWrapper(Integer workspaceId, Integer qtyOfGetWSIdRequests) {
			this.workspaceId = workspaceId;
			this.qtyOfGetWSIdRequests = qtyOfGetWSIdRequests;
		}
	}
}