source/objects/Bluescape_API_Token__c/Bluescape_API_Token__c.object-meta.xml
<CustomObject>
    <label>Bluescape API Token</label>
    <nameField>
        <label>Bluescape API Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bluescape API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Bluescape_API_Token__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/API_Version__c.field-meta.xml
<CustomField>
    <fullName>API_Version__c</fullName>
    <description>UAT1: v2
Production: &lt;blank&gt;</description>
    <label>API Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <type>TextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <label>Expires At</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Getting_Started_Workspace__c.field-meta.xml
<CustomField>
    <fullName>Getting_Started_Workspace__c</fullName>
    <description>Workspace ID of the getting started workspace to copy into the trial/demo org

Production: HrShLlpF3UdVrxrrILKt
Staging: 9GCvfOxhiyUTAO1bSMUC</description>
    <label>Getting Started Workspace</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Getting_Started_Workspace_Organization__c.field-meta.xml
<CustomField>
    <fullName>Getting_Started_Workspace_Organization__c</fullName>
    <description>The organization ID that contains the Getting Started workspace
Production: 4543
Stg1: 42586</description>
    <label>Getting Started Workspace Organization</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <defaultValue>&#39;apps.us&#39;</defaultValue>
    <description>Set to the instance being used. It will be embedded into the api url (ex - https://api.&lt;instance&gt;.bluescape.com)</description>
    <inlineHelpText>Examples: apps.us, stg1, uat1</inlineHelpText>
    <label>Instance</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Redirect_URI__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URI__c</fullName>
    <label>Redirect URI</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/objects/Bluescape_API_Token__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

source/classes/BluescapeIntegrationTest.cls
@isTest
public class BluescapeIntegrationTest {
    @TestSetup
    public static void setup() {        
        Bluescape_API_Token__c bluescapeAPIToken = new Bluescape_API_Token__c(
                Name = 'Bluescape_Api_Integration',
                Access_Token__c = 'accessToken',
                Client_ID__c = '123',
                Client_Secret__c = '123',
                Expires_At__c = 2000000000,
                Redirect_URI__c = 'https://localhost/callback',
                Refresh_Token__c = '123',
                Instance__c = 'stg1',
            	Getting_Started_Workspace__c = 'asdfasdfasdf123',
            	Getting_Started_Workspace_Organization__c = '1234',
            	API_Version__c = 'v1'
        );
        insert bluescapeAPIToken;
    }
    
    @isTest
    public static void testOrgRequest() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationRequestOrgMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.makeOrgRequest('test.org@gmail.com', 5);
        Test.stopTest();
        
        System.assertEquals(201, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testCreateUserRequest() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationCreateUserMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.createUserRequest(4512, 'test@gmail.com');
        Test.stopTest();
        
        System.assertEquals(200, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testGetUserForMakingAdminRequest() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationGetUserMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.getUserForMakingAdminRequest(4512, 'test@gmail.com');
        Test.stopTest();
        
        System.assertEquals(200, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testMakeUserAdminRequest() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationMakeUserAdminMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.makeUserAdminRequest(4512, 12839);
        Test.stopTest();
        
        System.assertEquals(200, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testCopyWorkspaceRequest() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationCopyWorkspaceMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.copyWorkspaceRequest('workspaceName');
        Test.stopTest();
        
        System.assertEquals(200, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testGetWorkspaceIdRequest() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationGetWorkspaceMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.getNewWorkspaceIdRequest('workspaceName');
        Test.stopTest();
        
        System.assertEquals(200, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testMoveWorkspaceToOrgRequest() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationMoveWorkspaceMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.moveWorkspaceToOrgRequest(12935, 754152);
        Test.stopTest();
        
        System.assertEquals(200, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testMakeWorkspacePublic() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationPublicWorkspaceMock());
        
        Test.startTest();
        BluescapeIntegration.ResponseWrapper responseWrapper = BluescapeIntegration.makeWorkspacePublic(754152);
        Test.stopTest();
        
        System.assertEquals(200, responseWrapper.responseCode);
    }
    
    @isTest
    public static void testExtendingOrgExpiration() {
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationExtendingOrgExpMock());
        
        Test.startTest();
        BluescapeIntegration.extendingOrgExpiration(10, 10);
        Test.stopTest();
    }
    
    @isTest
    public static void testRefreshAccessToken() {   
        Bluescape_API_Token__c bluescapeAPIToken = [
            	SELECT 
            		Refresh_Token__c, Expires_At__c, Access_Token__c, Client_ID__c, Client_Secret__c, Redirect_URI__c, Instance__c, Getting_Started_Workspace__c, Getting_Started_Workspace_Organization__c, API_Version__c
            	FROM 
            		Bluescape_API_Token__c LIMIT 1
        ];
        Test.setMock(HttpCalloutMock.class, new BluescapeIntegrationRefreshTokenMock());
        
        Test.startTest();
        BluescapeIntegration.refreshAccessToken(bluescapeAPIToken);
        Test.stopTest();
    }
}